<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="lewansoul_arm">
  <!-- Parameters for dimensions -->
  <xacro:property name="base_height" value="0.05"/>
  <xacro:property name="shoulder_length" value="0.2"/>
  <xacro:property name="elbow_length" value="0.2"/>
  <xacro:property name="wrist_length" value="0.15"/>
  <xacro:property name="gripper_size" value="0.1"/>
  
  <!-- Base Link -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.2 0.2 ${base_height}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1"/>
      </material>
    </visual>
  </link>
  
  <!-- Joint 1: Base Joint (servo 6) -->
  <joint name="base_joint" type="revolute">
    <origin xyz="0 0 ${base_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="shoulder_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="10" velocity="1.0"/>
  </joint>
  
  <!-- Shoulder Link -->
  <link name="shoulder_link">
    <visual>
      <geometry>
        <cylinder length="${shoulder_length}" radius="0.05"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
  </link>
  
  <!-- Joint 2: Shoulder Joint (servo 2) -->
  <joint name="shoulder_joint" type="revolute">
    <origin xyz="0 0 ${shoulder_length}" rpy="0 0 0"/>
    <parent link="shoulder_link"/>
    <child link="elbow_link"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>
  
  <!-- Elbow Link -->
  <link name="elbow_link">
    <visual>
      <geometry>
        <cylinder length="${elbow_length}" radius="0.04"/>
      </geometry>
      <material name="green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
  </link>
  
  <!-- Joint 3: Elbow Joint (servo 3) -->
  <joint name="elbow_joint" type="revolute">
    <origin xyz="0 0 ${elbow_length}" rpy="0 0 0"/>
    <parent link="elbow_link"/>
    <child link="wrist_pitch_link"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
  </joint>
  
  <!-- Wrist Pitch Link -->
  <link name="wrist_pitch_link">
    <visual>
      <geometry>
        <cylinder length="${wrist_length}" radius="0.03"/>
      </geometry>
      <material name="red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
  </link>
  
  <!-- Joint 4: Wrist Pitch Joint (servo 4) -->
  <joint name="wrist_pitch_joint" type="revolute">
    <origin xyz="0 0 ${wrist_length}" rpy="0 0 0"/>
    <parent link="wrist_pitch_link"/>
    <child link="wrist_roll_link"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1.57" upper="1.57" effort="5" velocity="1.0"/>
  </joint>
  
  <!-- Wrist Roll Link -->
  <link name="wrist_roll_link">
    <visual>
      <geometry>
        <!-- A shorter link representing the wrist roll -->
        <cylinder length="${wrist_length * 0.5}" radius="0.025"/>
      </geometry>
      <material name="yellow">
        <color rgba="1 1 0 1"/>
      </material>
    </visual>
  </link>
  
  <!-- Joint 5: Wrist Roll Joint (servo 5) -->
  <joint name="wrist_roll_joint" type="revolute">
    <origin xyz="0 0 ${wrist_length * 0.5}" rpy="0 0 0"/>
    <parent link="wrist_roll_link"/>
    <child link="gripper_link"/>
    <axis xyz="0 0 1"/>
    <limit lower="-3.14" upper="3.14" effort="5" velocity="1.0"/>
  </joint>
  
  <!-- Gripper Link -->
  <link name="gripper_link">
    <visual>
      <geometry>
        <box size="${gripper_size} 0.02 0.02"/>
      </geometry>
      <material name="orange">
        <color rgba="1 0.5 0 1"/>
      </material>
    </visual>
  </link>
  
  <!-- Joint 6: Gripper Joint (servo 1) -->
  <!-- Depending on your design, you might want to control the gripper fingers separately.
       Here we simply add a joint to orient the gripper. -->
  <joint name="gripper_joint" type="revolute">
    <origin xyz="0 ${gripper_size/2} 0" rpy="0 0 0"/>
    <parent link="gripper_link"/>
    <child link="gripper_end"/>
    <axis xyz="0 1 0"/>
    <limit lower="-0.5" upper="0.5" effort="2" velocity="1.0"/>
  </joint>
  
  <!-- Gripper End: Represents the end-effector for planning -->
  <link name="gripper_end">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <material name="magenta">
        <color rgba="1 0 1 1"/>
      </material>
    </visual>
  </link>
  
</robot>
