controller_manager:
  ros__parameters:
    update_rate: 30
    # use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    top_left_wheel_names: ['top_left_wheel_joint']
    top_right_wheel_names: ['top_right_wheel_joint']
    bottom_left_wheel_names: ['bottom_left_wheel_joint']
    bottom_right_wheel_names: ['bottom_right_wheel_joint']
    wheel_separation: 0.7
    wheel_radius: 0.07